version: '3.9'

services:
  wa-group-viz:
    image: ghcr.io/theopfr/whatsapp-group-visualized:latest
    ports:
      - "8050:8050"
    volumes:
      - ./data/config.json:/app/data/config.json
      - ./data/group-chat.csv:/app/data/group-chat.csv
    restart: unless-stopped
